language: java
jdk:
  - oraclejdk8

notifications:
  email:
    - zhgloss@gmail.com

cache:
  directories:
    - $HOME/.m2

install: mvn install

addons:
  apt:
    packages:
      - oracle-java8-installer

env:
  global:
    - secure: "DdIo5/SZDMF/VJSS5SuVwsjUGYl2AF9XKzGHZcBoUWwrlilb/tyePri6HuCwkK2AUUwl79udsxWYQcvVQjBIdz5UZHo6gyLGbfJT2vg+jnxSEk1KuteJx9+jN4gePoDqUjw695gWIf6H+ochcz6/xVlTD9IBpTxHCYlC8eRpmnrUK7+Fea1LJKp5XyqDIEKeU2+Hg/T8AulQ25wmzD9HHyYsyvq7sdS6fu47N+UtEeFklJiq9kENp+tUXVjhlmIXC5JCND+0tzw7zd+I7WfDbu+4TvtIQRCpwl8A/P11xXfIeT1zcC4abygO+dl0XPsKQ6ifW3pVZ2K2ovvcb6A94RuvtdLwWLXAgbSIHHaFjsWu4aQphCnXoP6Dl6YP/xwPZIcoIS4mtYojbaSNQH+m9KGd/555ZwwhELz7PFKHc2BbtLCSl0ObY4nPsQf3SvbqnL8FooHKia6dO1IIil8HqmS5DBYckonzaV0m6W2E0EEIwF1J8q07Cwo3Py42317snmt2GE5me5lTQufWiHFOuimWwxc2c5OFbrnFlDkBmRchPIxCIugGg3RRdFB1MRPmjB4hV7aOFLJb7mHmv+UTj351g9DKc9HQph6IGSf7hMSVjH6Q+QbjRCf/YulwbxE122FygjshrOR3l/JlSiybV2FqKLRx5mGae/DwOe3fvpo="
    - secure: "nqzIY4HVdXluD2KI/pGIF3R6mV8JB48hfhmx7UgW0I4SrBZnkLyXkUeVknokPkMVhhliFFOl7IMRKqTlzSeanlHPQXyA8wgvF59XQZc0kuUrgef1IqlliVhZTMaFbUp407Mi3nEZmAUKtsgLL3+uFiFAhfNB5NLGFFzCKJRpWyaCJh1261NxDzzJ2/Kqa5jcvhmJ9xY/YJHxiq40B9d1pZVMcFGeMMaV3F4D3eJHFVgy0K5qrpqI1G1Y8IUl8j+ZtDvax3Wu9VXqCs8z+CCmaJVN0RHgNdu2Ro80vkUBApZv9f/TVAm6dEoiqRZAK0qZYg+x+gBqn8F6UzvZvTj7LZD8J2UDF1WINnQFjefTp0RKQfL4lTX7xXKTXN89xST5YGGboa4pZJ+j+xkQFHXVRuF4Xr2tuvUwr6NVpSdJJTnI4UBd0gpFcWZ4XDrX8SI1TgxaLiRCSIbWBr1bP61RztyCgbS+LHY68OsPnu3WJ3VnQCF8V/KdEwQRZz/Lql6VkhhneZ9AKaqmn2yjiaLM6EqwdmFOR2XtXpNwQ/RY7LriVoa5r7QOO9JvVkDCizyEaq7EYkMwcCf7Oldb3Le1nlOuvan2qh7TP20QjZc/e+sFIy8TfOJCB/tAbXqm6K+lBdTtwpsHkJ6ZLDGK2alAvaBmuZfWx2Xd6H+ZVd5tPIM="

after_success:
  if [ "$TRAVIS_BRANCH" == "master" ] && [ ! -z "$TRAVIS_TAG" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] ; 
  then
    "curl -T target/zhgloss.war -u $TOMCAT_USER:$TOMCAT_PASSWORD http://www.zhgloss.com/manager/text/deploy?path=/zhgloss\\&update=true"
  fi
